apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet9-deploy-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planet9-1
  template:
    metadata:
      labels:
        app: planet9-1
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: planet9
        image: neptunesoftware/planet9:v2.0.4
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        ports:
        - containerPort: 8080
          name: planet9
